version: 1
formatters:
  simple:
    format: '[%(levelname)s] %(asctime)s - %(message)s'

handlers:

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ./log/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ./log/debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 1
    encoding: utf8

root:
  level: DEBUG
  handlers: [file, debug]